insert into Expenditure(UserId,Amount,Description,ExpDate,Remarks) values
(1,20,'Food',CURRENT_TIMESTAMP,'For eat'),
(1,15,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(1,10,'Water',CURRENT_TIMESTAMP,'For drink'),
(1,500,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(1,5,'Paper',CURRENT_TIMESTAMP,'For Paper'),

(2,21,'Food',CURRENT_TIMESTAMP,'For eat'),
(2,31,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(2,15,'Water',CURRENT_TIMESTAMP,'For drink'),
(2,700,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(2,4,'Paper',CURRENT_TIMESTAMP,'For Paper'),

(3,50,'Food',CURRENT_TIMESTAMP,'For eat'),
(3,25,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(3,10,'Water',CURRENT_TIMESTAMP,'For drink'),
(3,800,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(3,15,'Paper',CURRENT_TIMESTAMP,'For Paper'),

(4,33,'Food',CURRENT_TIMESTAMP,'For eat'),
(4,15,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(4,11,'Water',CURRENT_TIMESTAMP,'For drink'),
(4,530,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(4,5,'Paper',CURRENT_TIMESTAMP,'For Paper'),

(5,22,'Food',CURRENT_TIMESTAMP,'For eat'),
(5,15,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(5,11,'Water',CURRENT_TIMESTAMP,'For drink'),
(5,510,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(5,5,'Paper',CURRENT_TIMESTAMP,'For Paper'),

(6,40,'Food',CURRENT_TIMESTAMP,'For eat'),
(6,15,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(6,13,'Water',CURRENT_TIMESTAMP,'For drink'),
(6,400,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(6,4,'Paper',CURRENT_TIMESTAMP,'For Paper'),

(7,21,'Food',CURRENT_TIMESTAMP,'For eat'),
(7,17,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(7,12,'Water',CURRENT_TIMESTAMP,'For drink'),
(7,540,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(7,8,'Paper',CURRENT_TIMESTAMP,'For Paper'),

(8,16,'Food',CURRENT_TIMESTAMP,'For eat'),
(8,24,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(8,12,'Water',CURRENT_TIMESTAMP,'For drink'),
(8,800,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(8,12,'Paper',CURRENT_TIMESTAMP,'For Paper'),

(9,50,'Food',CURRENT_TIMESTAMP,'For eat'),
(9,13,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(9,33,'Water',CURRENT_TIMESTAMP,'For drink'),
(9,900,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(9,15,'Paper',CURRENT_TIMESTAMP,'For Paper'),

(10,80,'Food',CURRENT_TIMESTAMP,'For eat'),
(10,25,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(10,30,'Water',CURRENT_TIMESTAMP,'For drink'),
(10,500,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(10,5,'Paper',CURRENT_TIMESTAMP,'For Paper'),

(11,100,'Food',CURRENT_TIMESTAMP,'For eat'),
(11,15,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(11,10,'Water',CURRENT_TIMESTAMP,'For drink'),
(11,200,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(11,5,'Paper',CURRENT_TIMESTAMP,'For Paper'),

(12,25,'Food',CURRENT_TIMESTAMP,'For eat'),
(12,12,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(12,13,'Water',CURRENT_TIMESTAMP,'For drink'),
(12,510,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(12,7,'Paper',CURRENT_TIMESTAMP,'For Paper'),

(13,18,'Food',CURRENT_TIMESTAMP,'For eat'),
(13,17,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(13,13,'Water',CURRENT_TIMESTAMP,'For drink'),
(13,700,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(13,5,'Paper',CURRENT_TIMESTAMP,'For Paper'),

(14,20,'Food',CURRENT_TIMESTAMP,'For eat'),
(14,15,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(14,17,'Water',CURRENT_TIMESTAMP,'For drink'),
(14,800,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(14,5,'Paper',CURRENT_TIMESTAMP,'For Paper'),

(15,81,'Food',CURRENT_TIMESTAMP,'For eat'),
(15,17,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(15,12,'Water',CURRENT_TIMESTAMP,'For drink'),
(15,500,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(15,8,'Paper',CURRENT_TIMESTAMP,'For Paper'),

(16,200,'Food',CURRENT_TIMESTAMP,'For eat'),
(16,15,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(16,10,'Water',CURRENT_TIMESTAMP,'For drink'),
(16,500,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(16,5,'Paper',CURRENT_TIMESTAMP,'For Paper'),

(17,150,'Food',CURRENT_TIMESTAMP,'For eat'),
(17,80,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(17,10,'Water',CURRENT_TIMESTAMP,'For drink'),
(17,500,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(17,5,'Paper',CURRENT_TIMESTAMP,'For Paper'),

(18,90,'Food',CURRENT_TIMESTAMP,'For eat'),
(18,18,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(18,10,'Water',CURRENT_TIMESTAMP,'For drink'),
(18,520,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(18,9,'Paper',CURRENT_TIMESTAMP,'For Paper'),

(19,22,'Food',CURRENT_TIMESTAMP,'For eat'),
(19,18,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(19,12,'Water',CURRENT_TIMESTAMP,'For drink'),
(19,503,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(19,8,'Paper',CURRENT_TIMESTAMP,'For Paper'),

(20,21,'Food',CURRENT_TIMESTAMP,'For eat'),
(20,15,'Fruit',CURRENT_TIMESTAMP,'For eat'),
(20,10,'Water',CURRENT_TIMESTAMP,'For drink'),
(20,500,'Rent',CURRENT_TIMESTAMP,'For Rent'),
(20,5,'Paper',CURRENT_TIMESTAMP,'For Paper')